### ISSUE TITLE
Support TensorFlow 2.5

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/profiler#344]
I attempted to run TensorFlow Profiler on TensorFlow 2.5 by running the Colab Notebook from https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras .  The result is that Tensorboard loads, but the Profiler section just spins:
![image](https://user-images.githubusercontent.com/8866793/126585512-7bb4aa97-5d5e-4eef-b786-359c12d6cb9a.png)

Does TensorBoard Profiler support TensorFlow 2.5+?  If it doesn't, should the documentation be updated?

**Comment by 8bitmp3** [comment]
Hi, for now try the following by adding an extra flag:

```
%tensorboard --logdir=logs --load_fast=false
```

instead of:

```
%tensorboard --logdir=logs
```

Look out for the PROFILE tab next to TIME SERIES in the top bar if you can't find it in the dropdown menu.

https://github.com/tensorflow/tensorboard/issues/5088
https://github.com/tensorflow/profiler/issues/298
https://github.com/tensorflow/profiler/pull/307

cc @Terranlee @Jimicy @yisitu

**Comment by jeisinge** [comment]
Works for me.  Thank you!

**Comment by 8bitmp3** [comment]
Hi @jeisinge the latest Profiler plugin v2.5 (`pip install tensorboard_plugin_profile` (or `tensorboard_plugin_profile==2.5.0`)) should have the fix. You can launch TensorBoard with `%tensorboard --logdir=logs` and select Profiler. Thank you @yisitu.

**Comment by yisitu** [comment]
You are welcome!

**Comment by jeisinge** [comment]
Thank you --- I am testing now.

**Comment by jeisinge** [comment]
It appears to be working.  Thank you!!!
