### ISSUE TITLE
What's kernel launch time?

### ISSUE THREAD

**Issue by leasunhy** [tensorflow/profiler#8]
The performance summary shows that my model spend ~50% time in the "kernel launch" step.
I find other items easy to understand, but I have no idea what "kernel launch" is, and how I can reduce its time consumption.
I do complicated preprocessing to my data using the `tf.data.Dataset` APIs, but the summary shows that I spend no time on it. Could the preprocessing be the real cause of the high "kernel launch" time consumption?

![image](https://user-images.githubusercontent.com/5578454/79732384-2f132080-8326-11ea-8a80-7b0f9e5363b6.png)

Thanks!

**Comment by ckluk** [comment]
Hi,

"Kernel Launch" time is the time that the CPU spends on launching the GPU
compute kernels on the device.
It is different from the data preprocessing time in tf.data, which will be
counted as "Host Compute" time in this case.
If possible, can you upload your entire profile log directory so that I can
take a closer look at it?
Thanks,
-ck

**Comment by ckluk** [comment]
Now I see that there is no "Host Compute" time in your step-time graph. It is possible that the tf.data preprocessing time is overlapped with the kernel-launch time. In that case, we will still classify those time as kernel-launch time. Again, if you send me the log, I can understand this better.

**Comment by leasunhy** [comment]
Here you are. It's a bit large...
[profiler_log.zip](https://github.com/tensorflow/profiler/files/4509046/profiler_log.zip)

Thanks!

**Comment by ckluk** [comment]
Thanks for providing the log. After inspecting it, I believe that the kernel-launch time is actually overlapped with the tf.data preprocessing time on the CPU. It is possible that the tf.data preprocessing interferes with the kernel launching. You can't do much with the kernel launching, but you can try to reduce the interference of tf.data preprocessing by:
(1) Using more parallelism in tf.data preprocessing (https://www.tensorflow.org/guide/data_performance)
(2) Using a more powerful CPU
(3) Offloading some of the data preprocessing to GPU

**Comment by ckluk** [comment]
Can you try one thing:
set the environment variable TF_GPU_THREAD_MODE=gpu_private
This will prevent tf.data from interfering the threads that launch kernels on the GPU.

**Comment by leasunhy** [comment]
I optimized my data pipeline and the kernel launch time dropped significantly, so my training code now does not suffer from performance issues any more. Thanks for your explanation @ckluk !

If for improving the profiler you need the logs after setting the environment variable, I can help to  collect them.

**Comment by ckluk** [comment]
Nice to know that the performance issues are gone.
Yes, for improving the profiler, it would be great if we can get:
(1) The profile after setting the environment variable
(2) The profile with all your optimizations

Thanks a lot!
-ck

**Comment by JCobbles** [comment]
> Thanks for providing the log. After inspecting it, I believe that the kernel-launch time is actually overlapped with the tf.data preprocessing time on the CPU. It is possible that the tf.data preprocessing interferes with the kernel launching. You can't do much with the kernel launching, but you can try to reduce the interference of tf.data preprocessing by:
> (1) Using more parallelism in tf.data preprocessing (https://www.tensorflow.org/guide/data_performance)
> (2) Using a more powerful CPU
> (3) Offloading some of the data preprocessing to GPU

Hi there! How did you determine that tf.data preprocessing was responsible for the high Kernel Launch time? I have a similar problem with over 80% spent on kernel launch but not sure how to determine what is responsible in particular.

**Comment by ckluk** [comment]
What I did was to go to the trace_viewer to see if kernel-launch events are
overlapped with tf.data events.
Another possible reason for large percent of time spent on kernel launch is
that the GPU kernels are too short in execution time, and as a result the
kernel launching overhead dominates.

**Comment by carusyte** [comment]
Hi @ckluk , glad to find your answer here. I'm experiencing the same issue with high 'kernel launch' time, and I did try to set the environment variable `TF_GPU_THREAD_MODE=gpu_private` but in vain. How come...

<img width="1511" alt="Screen Shot 2020-06-02 at 9 38 23 PM" src="https://user-images.githubusercontent.com/1680881/83526870-a3420600-a519-11ea-87e7-c86b83401d52.png">

And here's the profile if you're interested to dig into it.
[profile.zip](https://github.com/tensorflow/profiler/files/4717511/profile.zip)

**Comment by ckluk** [comment]
Hi,

I took a look at the trace viewer result in your profile. It seems that the
spikes in step time are related to the use of py_func.
Did you use py_func in your model?
[image: image.png]

**Comment by carusyte** [comment]
Thanks for your swift reply. I used `tf.numpy_function` to be exact. I can barely remember how I came to this function as I was struggling with data loading from MySQL via `tf.data` pipeline, it was my final resort due to nested data structure (e.g. a dict) and compatibility with eager mode or something...

Should I remove/replace it with something else? Here's the code pertaining to this part in case you're interested:

```
def mapfunc(bno):
    ret = tf.numpy_function(func=_loadTrainingData,
                            inp=[bno],
                            Tout=[tf.float32, tf.int32, tf.float32])
            # f = py_function(func=_loadTrainingData,
            #                 inp=[bno],
            #                 Tout=[{
            #                     'features': tf.float32,
            #                     'seqlens': tf.int32
            #                 }, tf.float32])
    feat, seqlens, corl = ret

    feat.set_shape((None, max_step, feat_size))
    seqlens.set_shape((None, 1))
    corl.set_shape((None, 1))

    return {'features': feat, 'seqlens': seqlens}, corl

ds_train = tf.data.Dataset.from_tensor_slices(bnums).map(
    lambda bno: tuple(mapfunc(bno)),
    _prefetch).prefetch(_prefetch)
```

**Comment by ckluk** [comment]
I could be wrong, but this use of numpy functions seems to be causing the
slowdown (in other words, those numpy functions are on the critical path).
If you can replace them with a faster alternative, it would probably help.

**Comment by keewawa** [comment]
I'm on the same boat - the kernal lunch time is exceptionally high.  TF_GPU_THREAD_MODE=gpu_private did not help in my case either

![Capture](https://user-images.githubusercontent.com/4408568/83673195-16409080-a59d-11ea-89bd-88987e191b7f.PNG)

I also include the profile files here. Any insights will be very much appreciated! thx in advance!
[profile.zip](https://github.com/tensorflow/profiler/files/4725405/profile.zip)

**Comment by ckluk** [comment]
Hi Yan

I looked at your profile. I think the cause of the high kernel-launch
overhead is that the granularity of GPU kernel sis too small and so the
launching overhead dominates. There are two possible ways which may help:
(1) Use the XLA compiler, which can fuse multiple TF Ops into the same
kernel (see https://www.tensorflow.org/xla).
(2) Rewrite your TF code in a way to create larger granularity of
computation on the GPU.

Ccing sanjoy@google.com who knows this topic much better.

Thanks,
-ck

**Comment by sanjoy** [comment]
CC @cheshire

I agree with both of CK's recommendations.

**Comment by keewawa** [comment]
Thank you for your insights!

**Comment by zzjjbb** [comment]
Hi, I'm also experiencing extremely high kernel launch time:

![图片](https://user-images.githubusercontent.com/31069326/84905644-ebffd000-b07e-11ea-9cfb-722025bd99db.png)

Here is the raw profile data  
[2020_06_11_14_32_06.zip](https://github.com/tensorflow/profiler/files/4792904/2020_06_11_14_32_06.zip)

I tried to write everything in tf ops and use `@tf.function`, but it seems that the performance is even as low as computing on CPU. This really annoying me for weeks. Any helpful idea will be greatly appreciated!

**Comment by zzjjbb** [comment]
I tried to force compile using `@tf.function(experimental_compile=True)` but it failed. It says there are uncompilable nodes like this:
```
FFT2D_3: unsupported op: No registered 'FFT2D' OpKernel for XLA_CPU_JIT devices compatible with node {{node FFT2D_3}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: Tcomplex=DT_COMPLEX128
	Stacktrace:
		Node: StatefulPartitionedCall, function: 
		Node: FFT2D_3, function: __forward_model_922
```

**Comment by ckluk** [comment]
As I mentioned before, I think XLA may help. Ccing Sanjoy for the XLA issue
that you encountered.

**Comment by sanjoy** [comment]
As the error message says, we don't yet support complex128 on FFT2D.  As a workaround can you try using FFT2D with complex64?

The right fix is to add support for complex128 FFT2D, but we don't have cycles to look into this in the next few weeks at least.  But I'm happy to review PRs adding such support.

**Comment by Slyne** [comment]
@ckluk  Hi, I also encounter this problem. After checking the profiles uploaded, it's still difficult for me to find the exact operations that I should edit in my codes. It seems there are frequent ops between host and device. Not sure if my guess is correct. Could you help me?
[Uploading 2021_01_13_19_07_07.zip…]()
![StepTime](https://user-images.githubusercontent.com/6286804/104453007-be601280-55de-11eb-8498-8a4d4649cd85.JPG)

**Comment by ckluk** [comment]
Hi Slyne,

Usually, high kernel launch overhead is not due to a particular op.
Instead, it is because there is insufficient computation in the ops
executed on the device to amortize the kernel launch overhead. So,
following suggestions from one of my previous replies may still be helpful:
(1) Use the XLA compiler, which can fuse multiple TF Ops into the same
kernel (see https://www.tensorflow.org/xla).
(2) Rewrite your TF code in a way to create larger granularity of
computation on the GPU.
In particular, have you tried (1)?

**Comment by Slyne** [comment]
@ckluk  Thank you!
Yes, I've enabled XLA. 
It turns out I should not measure the beginning steps of a training epoch because my data is not equally distributed. The first serveral steps have much smaller size data.  
After changing the measure steps to be in the middle part of an epoch, I found the the bottleneck is IO.  I have over 1000000 sample files to read. At first, I used parallel_map to read these files as training goes but the IO problem cannot be solved. Now I use tf-records to store the data on disk and the performance seems much better. But tf profiler still complains ops on host should be as smaller as possible. (I don't have any preprocessing steps on host.)
My dataset is audio samples with their transcripts. The sample shape can be quite dynamic. Not sure if it would be better if I pad the samples to the same size (serveral buckets)?

**Comment by ydennisy** [comment]
@ckluk thanks for a great tool.

I am having the same issue as others on this thread with a large time spent on kernel launch.

I have set `TF_GPU_THREAD_MODE` (btw, is there a way to validate this has had the desired effect?), and I have also setup XLA which is working looking at the profiler trace view, but with no real improvement - the GPU is idle most of the time, yet my program is not I/O bound.

Do you have some other suggestions one can explore?

Thanks in advance,
D

**Comment by cengjingmengxiang** [comment]
@leasunhy what did you do in data pipeline? I meet the same question...

**Comment by Garett-MacGowan** [comment]
I am facing ]similar issues. Enabling XLA gave me about a 2X if my notes are correct. Things seem slower than they should be given that my GPU and CPU are both underutilized. According to task manager, CUDA usage is sitting around 30% and CPU usage is sitting around 20%. GPU memory sitting at about 0.6GB/4GB.

I am using TF data with parallel interleaves and maps to read and preprocess my data. Tensorboard Profiling overview page says "Your program is NOT input-bound because only 0.1% of the total step time sampled is waiting for input. Therefore, you should focus on reducing other time."

I am using a small batch size (8), but am trying to compensate for the lost computational efficiency by using the `steps_per_execution` parameter of model.compile in Keras.

I am compiling a custom sub-classed Keras model and layers.

I frequently receive "SubProcess ended with return code: 0" during my training process, which seems to interfere with training time and might be correlated with the kernel launch time. Not sure what it is caused by.

**Comment by SysuJayce** [comment]
hello everyone,

I am facing the same issue with TF2.4.1 + cuda11.0 + P40 GPU.

Below is the trace viewer, but I dont know how to findout what is the problem.

Can anyone please give some help?
[tensorboard.tar.gz](https://github.com/tensorflow/profiler/files/6292479/tensorboard.tar.gz)

![image](https://user-images.githubusercontent.com/12313888/114316165-fb339b00-9b34-11eb-98f8-a95d89f578a9.png)

![image](https://user-images.githubusercontent.com/12313888/114316125-c7587580-9b34-11eb-99ab-89411ad74437.png)

**Comment by liyuan97** [comment]
> hello everyone,
> 
> I am facing the same issue with TF2.4.1 + cuda11.0 + P40 GPU.
> 
> The GPU utilization is only 40%.
> 
> I have tried the `XLA`, but unfortunately it cant run with distributed training.
> 
> Below is the trace viewer, but I dont know how to findout what is the problem.
> 
> Can anyone please give some help? [tensorboard.tar.gz](https://github.com/tensorflow/profiler/files/6292479/tensorboard.tar.gz)
> 
> ![image](https://user-images.githubusercontent.com/12313888/114316165-fb339b00-9b34-11eb-98f8-a95d89f578a9.png)
> 
> ![image](https://user-images.githubusercontent.com/12313888/114316125-c7587580-9b34-11eb-99ab-89411ad74437.png)

I Have same problem with u

**Comment by utkarshgupta137** [comment]
To debug this, I removed all the layers and then added each layer one by one. I found that LSTM/GRU layers added the majority (90%) of the kernel launch time. Furthermore, kernel launch time was directly proportional to the RNN length.
I guess this is expected because some computation of the RNN has to be done on the CPU & it has to get data from GPU & then launch a new kernel for each step of the RNN.

To improve training time, I modified some parameters to ensure that cuDNN was used by RNN layers (https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU) & also switched from LSTM to GRU.
For the inference time, the only way to get an acceptable response time for my application was to use the CPU for inference. With CPU, inference time decreased from 120ms to 20ms.
This makes sense too, as my model compromised of 7 Embeddings, 10 GRUs, & 6 Dense layers. So it was very RNN heavy & benefitted a lot from the computations taking place on the CPU only.

Using CPU also made sense for me because at 20ms, I could do 50 batches/sec with a batch size 16 = 800 requests/sec which was more than enough for my requirements & a 32-core CPU instance cost half as much as the cheapest GPU instance.

**Comment by hardstuding** [comment]
I have the same problem. Could anyone help!
TF 2.14, CUDA 11.8,  cuDNN 8.9.6, python 3.11
CPU usage 10%, IO 2% or less, GPU fluctuate between 0% and 90+%。
GPU is Tesla V100
I have used num_parallelism = auto, prefetch, my data is simple, so almost not need to do some feature engine.
I also try os.environ['TF_GPU_THREAD_MODE']='gpu_private'.

But all is not benefit.


![image](https://github.com/user-attachments/assets/9b55bf10-b2dd-4218-867f-c363cb9ba595)
![image](https://github.com/user-attachments/assets/75b7a968-432b-4957-ad13-3edc6cccedfa)

This is train profiler log [gpu_opitimize.zip](https://github.com/user-attachments/files/18173422/gpu_opitimize.zip)

This is my main code,  contain tf.data and model
[GPU_optimize.zip](https://github.com/user-attachments/files/18173467/GPU_optimize.zip)

**Comment by hardstuding** [comment]
> I have the same problem. Could anyone help! TF 2.14, CUDA 11.8, cuDNN 8.9.6, python 3.11 CPU usage 10%, IO 2% or less, GPU fluctuate between 0% and 90+%。 GPU is Tesla V100 I have used num_parallelism = auto, prefetch, my data is simple, so almost not need to do some feature engine. I also try os.environ['TF_GPU_THREAD_MODE']='gpu_private'.
> 
> But all is not benefit.
> 
> ![image](https://private-user-images.githubusercontent.com/51326485/396456917-9b55bf10-b2dd-4218-867f-c363cb9ba595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDE4MTAsIm5iZiI6MTczNDUwMTUxMCwicGF0aCI6Ii81MTMyNjQ4NS8zOTY0NTY5MTctOWI1NWJmMTAtYjJkZC00MjE4LTg2N2YtYzM2M2NiOWJhNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA1NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MzU4NzUwMjZkMzJhNDdiZTI1M2UwNWY5NTA4MDdiNGM0ZWZiYmI3NWM3MWNiOTY3MDhkNzQ0ZjcxOWRjNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UR0K6as85N1Z6PcXGGLa0arbj2lOCxiT3mzuFU4-w4I) ![image](https://private-user-images.githubusercontent.com/51326485/396457685-75b7a968-432b-4957-ad13-3edc6cccedfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDE4MTAsIm5iZiI6MTczNDUwMTUxMCwicGF0aCI6Ii81MTMyNjQ4NS8zOTY0NTc2ODUtNzViN2E5NjgtNDMyYi00OTU3LWFkMTMtM2VkYzZjY2NlZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA1NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NWE5MzY5NDRjZGNlYTU2MTVhMzA4M2FlMmViMDcwZTQ3MGU2NGEyZmViYzIxN2JkMmIzZDEzODI1MDUyOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UFa-N5m6CuYdEZkBxeOvoDuitEUaRz5EhmQCc_bq9XM)
> 
> This is train profiler log [gpu_opitimize.zip](https://github.com/user-attachments/files/18173422/gpu_opitimize.zip)
> 
> This is my main code, contain tf.data and model [GPU_optimize.zip](https://github.com/user-attachments/files/18173467/GPU_optimize.zip)

I almost solve this problem by remove my env and reinstall tensorflow==2.17.Then each batch cost 2s, but now tensor profiler can't be used.
